### ISSUE TITLE
Latest code not pushed to NPM

### ISSUE THREAD

**Issue by aj-may** [howdyai/botkit-storage-redis#11]

**Comment by peterswimm** [comment]
This should be fixed in the next major update (hopefully this week!)

**Comment by cms5x** [comment]
(I assume this issue is the root cause of the problem I experienced): 
I Installed via npm, but found it lacked the recent change to add custom methods (beyond 'users', 'teams', 'channels'), cloning from gitHub solved that, but spent a little while pulling my hair out thinking it was something wrong on my end.  Looking forward to corrected npm deployment which will make automated deployments easier.

**Comment by peterswimm** [comment]
Ive created a ticket for the team to take a look, will post an update when this is verified/fixed.

**Comment by bambielli** [comment]
It would be great to get this published to NPM! I'd like to use the remove method.

**Comment by colestrode** [comment]
This should be a minor version bump since new features were added. This should only take a few seconds, it would be great to have npm publishes as a part of merging into master. Since this is a small lib without long-range development in process, regularly merging seems like a good strategy.

I recommend using the `npm version` command, it handles bumping the version and tagging the repo. These are the commands I use for bumping libs (often I have the `git push` as a postpublish npm hook)

```
npm version minor
npm publish
git push origin master --follow-tags
```

**Comment by benbrown** [comment]
@colestrode whoa that is super handy!

I am going to do this now.

**Comment by benbrown** [comment]
Done! 1.1.0 is now live on npm.

Sorry for the delay.

**Comment by aj-may** [comment]
Thanks @benbrown
